set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" "call vundle#begin('~/some/path/here')

" " let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Nerd Tree
Plugin 'scrooloose/nerdtree'
" TagList
Plugin 'vim-scripts/taglist.vim.git'
" Airline
Plugin 'bling/vim-airline.git'
" YCM
"if has("gui_macvim")
    "Plugin 'https://github.com/Valloric/YouCompleteMe.git'
    "let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
"endif

" " The following are examples of different formats supported.
" " Keep Plugin commands between vundle#begin/end.
" " plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" " plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" " Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" " git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" " The sparkup vim script is in a subdirectory of this repo called vim.
" " Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" " Avoid a name conflict with L9
" Plugin 'user/L9', {'name': 'newL9'}
"
" " All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" " To ignore plugin indent changes, instead use:
" "filetype plugin on
" "
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append set!set to update or just
" :PluginUpdate
" :PluginSearch foo - searches for foo; append set!set to refresh local
" cache
" " :PluginClean      - confirms removal of unused plugins; append set!set to
" auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line

set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

colorscheme badwolf
syntax enable           " shortname for a command
set tabstop=4           " Tab convert rule when open a file
set softtabstop=4
set cursorline          " highlight current cursor line
set wildmenu            " autocompletes
filetype indent on      " load filetype-specific indent files
filetype plugin on
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]

exec ":set nu!"
exec ":set expandtab"
exec ":set shiftwidth=4"

set cindent

set encoding=utf-8
set fileencodings=utf-8,chinese,latin-1
if has("win32")
set fileencoding=chinese
else
set fileencoding=utf-8
endif
"解决菜单乱码
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
"解决consle输出乱码
language messages zh_CN.utf-8

" gpf def
map <F9> :w <CR> :! python %<CR>
map <F8> :w <CR> :! g++ -g  % -std=c++11 -o %< <CR> :! ./%< 
map J $
map <F2> :NERDTreeToggle<CR> :set columns=100<CR>
map <F3> :TlistToggle<CR>
imap <S-Tab> <C-N>
map <C-f> q:p0i/<CR>
map <C-s> <Esc>:w<CR>
map <C-x> <Esc>:q<CR>
nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-j> :wincmd j<CR>
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-l> :wincmd l<CR>
nmap <Leader>s :w<cr>
map <C-a> ggvG
map <C-k> :pyf /usr/local/Cellar/clang-format/2015-09-01/share/clang/clang-format.py<cr>
imap <C-k> :pyf /usr/local/Cellar/clang-format/2015-09-01/share/clang/clang-format.py<cr>

"  map for recording
nnoremap Q @q
vnoremap Q :norm :@q

"open nerdtree

" autocmd VimEnter * NERDTree
